openscad -o sae-prusa\bar-clamp.stl source\bar-clamp.scad
openscad -o sae-prusa\bearing-guide.stl source\bearing-guide.scad
openscad -o sae-prusa\belt-clamp-nut-holder.stl source\belt-clamp-nut-holder.scad
openscad -o sae-prusa\belt-clamp.stl source\belt-clamp.scad
openscad -o sae-prusa\coupling.stl source\coupling.scad
openscad -o sae-prusa\endstop-holder.stl source\endstop-holder.scad
openscad -o sae-prusa\frame-vertex.stl -D 'basefoot=false' source\frame-vertex.scad
openscad -o sae-prusa\frame-vertex-foot.stl source\frame-vertex.scad
openscad -o sae-prusa\printable-bushing.stl source\printable-bushing.scad
openscad -o sae-prusa\printable-bushing-lm8uu.stl source\printable-bushing-lm8uu.scad
openscad -o sae-prusa\pulley.stl source\pulley.scad
openscad -o sae-prusa\rod-clamp.stl source\rod-clamp.scad
openscad -o sae-prusa\sanguinololu-holder.stl source\sanguinololu-holder.scad
openscad -o sae-prusa\wade.stl source\wade.scad
openscad -o sae-prusa\wade-big.stl source\wade-big.scad
openscad -o sae-prusa\wade-small.stl source\wade-small.scad
openscad -o sae-prusa\x-carriage.stl source\x-carriage.scad
openscad -o sae-prusa\x-end-idler.stl source\x-end-idler.scad
openscad -o sae-prusa\x-end-motor.stl source\x-end-motor.scad
openscad -o sae-prusa\y-bushing.stl source\y-bushing.scad
openscad -o sae-prusa\ybrac-t.stl source\ybrac-t.scad
openscad -o sae-prusa\z-motor-mount.stl source\z-motor-mount.scad
